version: '3'

services:
    nginx-proxy:
        build: nginx-proxy
        restart: always
        ports:
        - "80:80"
    nginx-static:
        build: nginx-static
        restart: always
    flask-test:
        build: flask-test
        restart: always
        ports:
        - "5000:80"
    flask-news:
        build: flask-news
        ports:
        - "5001:80"
    shiny-test:
        build: shiny-test
        ports:
        - "3838:3838"
