version: '3'

services:
    nginx-proxy:
        build: nginx-proxy
        restart: always
        ports:
        - "80:80"
    nginx-static:
        build: nginx-static
        restart: always
        ports:
        - "5001:80"
    flask-test:
        build: flask-test
        restart: always

